#!/usr/bin/env bash

if [[ -f $(dirname $0)/vars.env ]]; then
    source $(dirname $0)/vars.env
    [[ ! -z $CLONE_DEPS ]] && export CLONE_DEPS
    [[ ! -z $TEST_USING ]] && export TEST_USING
fi

docker run -it --rm \
	-e CLONE_DEPS \
    -e TEST_USING \
    -v /var/run/docker.sock:/var/run/docker.sock \
	-v $(pwd):/repos/app \
    callforamerica/testdocker
