#!/usr/bin/env bash

base=$(dirname $0)

if [[ -f $base/vars.env ]]; then
    source $base/vars.env
    export $(cut -d'=' -f1 $base/vars.env | xargs)
fi

docker run -it --rm \
	-e CLONE_DEPS \
    -v /var/run/docker.sock:/var/run/docker.sock \
	-v $(pwd):/repos/app \
    callforamerica/testdocker \
    python3 tests/tests.py
