addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=telephoneorg
  # DOCKER_PASS
  - secure: "uoKkrXS3GJprdJUIwhQhoE+o3NzTTZLnRI0zwnVC1SUxf/kPxhnD30+g9bkKUspRuUVXfrIdcuSzYGqVwHBuLaDyHWF9Uov1jTjMS2i9hvkbida/DPJLnfMyhwMPnkcfZElhh7/oUHAtkDvhk2qfb/ehB9UpSbK2irBVfmD4mKVZXVSfpclrAHvVzyaS1emN7unwY8uPqxvRO+u6F7Bn37njArIb0JXQay2oHZAP5wWld/LzNWic5LK8dVKjgLnR1r78vW0zwcq4HKzDf3hWte0IM25dDvtwZI6zecgls+KehD4/BX+/5g6P0qQC16XHnu+iq224uNIEB6nKuWB6ErqvNzw8NdnIWCKInd3xk8YuPTRmASiTA6kUT8Nwr6DLjNZbIZNaUCcgYLrLW+qVsReh+d2Hd0qRvPXQTn7SPxT81YqCN6bJY0zbG4dzOEOZDBawe9wt5rHO+ZAeuvVsvd2/PVllqeLrEA2nq2mHHnamyONkjRIpspz7YdBfe/6noOb1HYx/Mpr7iPsesUP+fSD7br9CZgAW6Lc6TeJ5rQIRX69vAlbueEdiZSI0VThHmu4PulqEkoIYIFOhvlUyZfM2riCCTHW02MLQOXrFaU1J5yCGOxKHOxZmAE1xNjtapj25ocbWZFiKMxOcHmYmwpgpfaKvTCEIlMeU81Qy8pk="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "uM2l8ZYMLRPvZtCZZu4HSuHIsjMmMIpjMNWu5v9UlmJM9eFW1DcJBFPQ/fLBtup4NvGcnBEA3yJYsXHNGIZIq7RmTAprWjTvR2GB0qMp0exyBd7lZfoOCzooVH7b0UaMVl6c/EvrZWN11bgVh3eTjHXFSJ7/4Y2wiaWxD6l+iFKYxDbnJ1Aa0tVS+R3/4on0aONvrzpJ5BJP340Y5xdidwi1pZHMKOOhsht7LannYTXIvAmoSzhtDfcOPI2t+ifArq9bO/4JlDo/pad7IZzrBsp5IgfEcE9MYbyJOPsFAeLwI1Ls3YX5+R4HlnPf6cWP7f7u1Br2xksD6JRcPk2Goqtx0vaJzJDOE90fgWb8dY6N/ZmIIMDMFnkZnMxIm2Eu4tKJCNOF6zz8hUacLfrRpccTbsL8c44X1RRqoLxPfIR9Cbs8wEiPrgFZpin4Bfw2lqdVXxIDwdq6OHHF2oy/buufu3DW5oiWEllh0XlfqKl6VuXCKfJwFCHanhuxebUorWn+EtdovjsJMHiPM+AdkmMmdp94yD4M8gNI9ZKW9OYM4AtN9pPVHH0+AyTtIg1LXpneb53b3AhdxD59/EFe2D5YOn2/Rmmzx5uTcShOMgY7vSJvJzIvyaLjYgeWlkGQ1sW1PXxqVkAF9dCvXw9QSDnSHITC0AyRJO5VXnQsRC0="
    on_success: always
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install invoke

install:
- pip install -e .

script: true

after_success:
- inv docker.build
- ci-tag-build
- hub-push
- hub-update-readme
