#!/usr/bin/env ash

set -e

tests_path=${2:-/repos/app/tests/tests.py}
base_path=$(dirname $tests_path)

printf 'Starting testdocker v%s\n\n' $TESTDOCKER_VERSION

if [[ ! -z $CLONE_DEPS ]]; then
    printf "Cloning deps: ${CLONE_DEPS//,/ }\n\n"
    for dep in ${CLONE_DEPS//,/ }; do
        cd .. > /dev/null 2>&1
        git clone https://github.com/$GITHUB_ORG/docker-${dep}
        cd - > /dev/null 2>&1
        printf '\n'
    done
fi

if [[ -f $base_path/requirements.txt ]] && \
    [[ $(awk NF $base_path/requirements.txt | wc -l | xargs) -gt 0 ]]; then
        printf "Installing requirements from $base_path/requirements.txt\n"
        pip3 install -r $base_path/requirements.txt
fi

if [[ ! -z $1 ]]; then
    set -- "$@"
else
    set -- "python" "$tests_path"
fi

exec "$@"
