#!/usr/bin/env bash

BASE=$(dirname $0)
IMAGE=${DOCKER_ORG:-telephoneorg}/testdocker:latest

if [[ $1 == 'local' ]]; then
    pip3 install --upgrade testdocker > /dev/null 2>&1
    python3 $BASE/tests.py
else
    docker pull $IMAGE
    docker run -it --rm \
        $([[ -f $BASE/vars.env ]] && echo '--env-file vars.env') \
        -v /var/run/docker.sock:/var/run/docker.sock \
    	-v $(pwd):/repos/app \
        $IMAGE \
        python3 tests/tests.py
fi
